# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/book-music',
                'doc_host': 'https://eric-austin.github.io',
                'git_url': 'https://github.com/eric-austin/book-music',
                'lib_path': 'book_music'},
  'syms': {'book_music.core': {'book_music.core.foo': ('core.html#foo', 'book_music/core.py')}}}
